name: Build and Deploy Todo Application

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Build & Push Backend Docker Image
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest -f backend/Dockerfile backend/
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest

      # 4. Build & Push Frontend Docker Image
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest -f frontend/Dockerfile frontend/
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest

      # 5. Deploy Backend to Render.com
      - name: Deploy Backend to Render
        run: |
          # If you have a deploy hook for the backend:
          curl -X POST ${{ secrets.RENDER_BACKEND_WEBHOOK_URL }}
        # If webhook isn't available, you can add conditional execution:
        continue-on-error: true

      # 6. Deploy Frontend to Render.com
      - name: Deploy Frontend to Render  
        run: |
          # If you have a deploy hook for the frontend:
          curl -X POST ${{ secrets.RENDER_FRONTEND_WEBHOOK_URL }}
        # If webhook isn't available, you can add conditional execution:
        continue-on-error: true

      # 7. Report Deployment Status
      - name: Report Deployment Status
        run: |
          echo "Backend image pushed to DockerHub: ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest"
          echo " Frontend image pushed to DockerHub: ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest"
          echo " Deployment to Render.com triggered"
